services:
  # UI Website (Docs with integrated Playground)
  akex:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: akex
    ports:
      - "3001:3001"
    command: npm run dev:akex
